### ISSUE TITLE
Build libfuse branch for xenix?

### ISSUE THREAD

**Issue by snhirsch** [jaylogue/retro-fuse#11]
I would really like to try the xenix branch on some TRS-80 Model 16 images, but it doesn't build on Ubuntu 24.04.  I have libfuse-dev installed but this happens at build time:

```
hirsch@thelio:/net/src/platforms/att/retro-fuse$ make
cc -std=c11 -g -Wall -O0 -fno-common -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -D_ATFILE_SOURCE -D_DARWIN_C_SOURCE -MMD -MP -I./src  -c -o src/fusecommon.o src/fusecommon.c
cc -std=c11 -g -Wall -O0 -fno-common -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -D_ATFILE_SOURCE -D_DARWIN_C_SOURCE -MMD -MP -I./src  -c -o src/v6fuse.o src/v6fuse.c
src/v6fuse.c: In function ‘retrofuse_parseinitfsopt’:
src/v6fuse.c:45:8: error: ‘struct retrofuse_config’ has no member named ‘initfs’
   45 |     cfg->initfs = 1;
      |        ^~
src/v6fuse.c:46:8: error: ‘struct retrofuse_config’ has no member named ‘initfsparams’
   46 |     cfg->initfsparams.isize = 0;
      |        ^~
src/v6fuse.c:47:8: error: ‘struct retrofuse_config’ has no member named ‘initfsparams’
   47 |     cfg->initfsparams.n = 24;
      |        ^~
src/v6fuse.c:48:8: error: ‘struct retrofuse_config’ has no member named ‘initfsparams’
   48 |     cfg->initfsparams.m = 3;
      |        ^~
```
Can you advise on what package provides those missing symbols?

**Comment by jaylogue** [comment]
This is a result of the WIP nature of the xenix branch.  I've made significant changes to the internal configuration structure (struct retrofuse_config) as part of supporting the rather more complicated disk layouts schemes used on Xenix systems (e.g. IBM PC's MBR or TRS-Xenix's "PVH" table).  However, I have yet to backport these changes to the other filesystem handlers, which results in the errors you're seeing.  To avoid this, simply  "make xenixfs" instead of just "make".

A word of caution: the xenix code is very much incomplete.  It currently only supports the TRS-Xenix "PVH" table layout, and only if there are no bad blocks in the bad block table.  I have done some limited manual testing, but there are no automated tests yet.

EDIT: corrected make command

**Comment by snhirsch** [comment]
Ah - ok.  It's actually 'make xenixfs' rather than xenixfuse.  I have it built and will let you know how it goes :-)

**Comment by snhirsch** [comment]
Can you give me a quick example of the required syntax?  It's complaining about needing an appropriate -o option, but no idea what that might be.

**Comment by jaylogue** [comment]
Sorry for the confusion about the make target.

The following command should work for TRS-XENIX v01.xx disk images:

`./xenixfs -o fstype=trsxenix1 ./test.dsk mnt`

Support for later versions of TRS-XENIX is not there yet.

**Comment by snhirsch** [comment]
Thanks!  I may be able to get you more information on the TRS-Xenix v3 filesystem if that would be of help.

**Comment by snhirsch** [comment]
No luck with mounting a TRS-XENIX v01.xx image:
```
xenixfs: ERROR: Failed to open disk device/container file: No such file or directory
```
I traced it a bit with gdb and discovered it's going wrong after calling dsk_getgeometry() in dskio.c.  Didn't spend a lot of time with it, but it seems not to believe the file is open and readable.  I know this is early in the game, so I'll check back in the near future.  There are many folks with Tandy 68k systems who can make use of this tool once it can handle v3 hard disk images.

**Comment by jaylogue** [comment]
I realized I hadn't pushed my latest change to the xenix branch, which probably explains the error you're seeing.

With the latest code I am able to mount and access an empty disk image that I created using TRS-Xenix v01.03 running on trs80gp (see attached).  The image is a DREM-style container (.dsk & .cfg file) containing an image with a PVH partition table and a single filesystem.  I mount it as follows:

`./xenixfs -o fstype=trsxenix1 ./trs-xenix-130-empty.dsk mnt`

>  There are many folks with Tandy 68k systems who can make use of this tool once it can handle v3 hard disk images.

Yep.  TRS-Xenix v3 was Unix System III based, which has a slightly evolved on-disk format from the earlier 7th-edition systems.  The changes aren't big, but I just haven't gotten to them yet.

Since I have no real hardware, nor any past hands-on experience, I going entirely by what I've learned online.  If you have any real-world disk images that you're able to share, I'd love get a copy.

[trs-xenix-130-empty.tar.gz](https://github.com/user-attachments/files/26845203/trs-xenix-130-empty.tar.gz)

**Comment by snhirsch** [comment]
I did another pull in the source tree, but now it dies with "external/inih/ini.h" missing.  

Here's a hard disk image from a working Xenix 3.x install: 

[model16.zip](https://github.com/user-attachments/files/26905811/model16.zip)

**Comment by jaylogue** [comment]
Thanks for the disk images.

```
(mkdir -p external; cd external; git clone https://github.com/benhoyt/inih.git)
```

should solve the build problem.  Eventually this code will be incorporated as a submodule.
